
repos:
-   repo: local
    hooks:
      - id: generate-schema
        name: generate-schema
        entry: python -m voice_commander.schema
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies:
          - pydantic
          - SpeechRecognition
          - thefuzz
          - setuptools
          - ahk
          - json-five

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: mixed-line-ending
        args: ["-f", "lf"]
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
-   repo: https://github.com/psf/black
    rev: '24.10.0'
    hooks:
    -   id: black
        args:
            - "-S"
            - "-l"
            - "120"
        exclude: ^(docs/.*)

-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
    -   id: reorder-python-imports
        args: [--py312-plus, --add-import, 'from __future__ import annotations']
        exclude: setup\.py

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'
    hooks:
    -   id: mypy
        args:
            - "--strict"
        exclude: ^(docs/.*|tests/.*|setup\.py|\.build\.py)
        additional_dependencies:
          - pydantic
          - SpeechRecognition
          - thefuzz
          - setuptools
          - ahk
          - json-five
          - pyyaml
          - types-PyYAML

-   repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
    -   id: flake8
        args:
          - "--ignore"
          - "E501,E704,E301,W503,E701"
        files: voice_commander\/.*
        exclude: ^(docs/.*)
