name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    environment: release
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: build
      shell: bash
      run: |
        python -m pip install --upgrade wheel setuptools build
        python -m build
    - name: Release PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: "dist/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
